version: '3'

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_BROWSER_OVERRIDE=chrome:2
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_BROWSER_OVERRIDE=firefox:2
    networks:
      - grid
      

networks:
  grid:
    driver: bridge
